# Generated by Django 5.2.3 on 2025-07-25 09:43

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_blog_timestamp_blog_updated'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='published',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
