# Generated by Django 5.2.3 on 2025-07-25 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_alter_blog_published'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='published',
            field=models.DateField(blank=True, null=True),
        ),
    ]
