# Generated by Django 5.2.3 on 2025-08-06 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_alter_recipeingredients_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipeingredients',
            name='quantity_as_float',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
