# Generated by Django 5.2.3 on 2025-09-03 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_recipeingredientsimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipeingredientsimage',
            name='image',
            field=models.ImageField(upload_to='recipes/'),
        ),
    ]
