# Generated by Django 5.2.3 on 2025-09-03 14:44

import recipes.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0005_alter_recipeingredientsimage_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipeingredientsimage',
            name='image',
            field=models.ImageField(upload_to=recipes.models.recipe_ingredient_image_upload_handler),
        ),
    ]
